addons/devposture: Fix compilation error with older JsonCpp libraries
Older Linux distributions (Ubuntu 20.04) ships JsonCpp v1.7, which
requires checking with the .empty() method.  That library version does
not have a boolean operator override which newer library versions seems
to have.

Without this fix, the compiler will abort with this error:

    ../addons/devposture/service.cpp: In member function ‘void DevPosture::Handler::method_run_checks(DBus::Object::Method::Arguments::Ptr) const’:
    ../addons/devposture/service.cpp:265:13: error: could not convert ‘ret_payload_json’ from ‘Json::Value’ to ‘bool’
      265 |         if (ret_payload_json)
          |             ^~~~~~~~~~~~~~~~
          |             |
          |             Json::Value
    ../addons/devposture/service.cpp: In member function ‘Json::Value DevPosture::Handler::create_merged_mapped_json(const Json::Value&) const’:
    ../addons/devposture/service.cpp:372:13: error: could not convert ‘mapped_json’ from ‘const Json::Value’ to ‘bool’
      372 |         if (mapped_json)
          |             ^~~~~~~~~~~
          |             |
          |             const Json::Value

Signed-off-by: David Sommerseth <davids@openvpn.net>